# Generated by Django 3.0.4 on 2020-04-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCharacter',
            fields=[
                ('char_id', models.AutoField(primary_key=True, serialize=False)),
                ('health', models.IntegerField()),
                ('mana', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('ar', models.IntegerField()),
                ('mr', models.IntegerField()),
                ('attack_range', models.IntegerField()),
                ('rarity', models.IntegerField()),
                ('crit_chance', models.IntegerField()),
            ],
        ),
    ]
