# Generated by Django 3.0.4 on 2020-04-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecharacter',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
