# Generated by Django 3.0.4 on 2020-04-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0002_basecharacter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecharacter',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
