# Generated by Django 3.0.4 on 2020-04-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0003_auto_20200401_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('attack', models.IntegerField()),
                ('penetration', models.IntegerField()),
                ('attack_speed', models.IntegerField()),
                ('rarity', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
