# Generated by Django 3.0.4 on 2020-04-02 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0005_character_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basecharacter',
            old_name='char_id',
            new_name='char_type',
        ),
        migrations.RenameField(
            model_name='baseitem',
            old_name='item_id',
            new_name='item_type',
        ),
        migrations.RemoveField(
            model_name='character',
            name='id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AddField(
            model_name='character',
            name='char_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='playerdata.BaseCharacter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='playerdata.BaseItem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='char_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
