# Generated by Django 3.0.4 on 2020-04-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0006_auto_20200402_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecharacter',
            name='char_type',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='baseitem',
            name='item_type',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
