# Generated by Django 3.0.4 on 2020-04-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0007_auto_20200402_2126'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['user'], name='playerdata__user_id_0645f2_idx'),
        ),
    ]
