# Generated by Django 3.0.4 on 2020-04-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0008_auto_20200403_0302'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['user'], name='playerdata__user_id_a5443c_idx'),
        ),
    ]
