# Generated by Django 3.0.4 on 2020-04-03 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('playerdata', '0009_auto_20200403_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('placement_id', models.AutoField(primary_key=True, serialize=False)),
                ('pos_1', models.IntegerField()),
                ('char_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playerdata.Character')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('elo', models.IntegerField(default=0)),
                ('name', models.CharField(default='new player', max_length=20)),
                ('default_placement', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playerdata.Placement')),
            ],
        ),
    ]
