# Generated by Django 3.0.4 on 2020-04-03 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0010_placement_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='char_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char_2', to='playerdata.Character'),
        ),
        migrations.AddField(
            model_name='placement',
            name='char_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char_3', to='playerdata.Character'),
        ),
        migrations.AddField(
            model_name='placement',
            name='char_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char_4', to='playerdata.Character'),
        ),
        migrations.AddField(
            model_name='placement',
            name='char_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char_5', to='playerdata.Character'),
        ),
        migrations.AddField(
            model_name='placement',
            name='pos_2',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='placement',
            name='pos_3',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='placement',
            name='pos_4',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='placement',
            name='pos_5',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='placement',
            name='char_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char_1', to='playerdata.Character'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='pos_1',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddIndex(
            model_name='userinfo',
            index=models.Index(fields=['elo'], name='playerdata__elo_d5bd90_idx'),
        ),
    ]
