# Generated by Django 3.0.4 on 2020-04-05 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0011_auto_20200403_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('pos_1', models.IntegerField(default=-1)),
                ('pos_2', models.IntegerField(default=-1)),
                ('pos_3', models.IntegerField(default=-1)),
                ('pos_4', models.IntegerField(default=-1)),
                ('pos_5', models.IntegerField(default=-1)),
                ('pos_6', models.IntegerField(default=-1)),
                ('char_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tchar_1', to='playerdata.Character')),
                ('char_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tchar_2', to='playerdata.Character')),
                ('char_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tchar_3', to='playerdata.Character')),
                ('char_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tchar_4', to='playerdata.Character')),
                ('char_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tchar_5', to='playerdata.Character')),
                ('char_6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tchar_6', to='playerdata.Character')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playerdata.Team'),
        ),
    ]
