# Generated by Django 3.0.4 on 2020-04-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0014_userstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecharacter',
            name='ar_scale',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basecharacter',
            name='attack_scale',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basecharacter',
            name='health_scale',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basecharacter',
            name='mr_scale',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
