# Generated by Django 3.0.4 on 2020-04-07 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0015_auto_20200406_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='exp',
            new_name='level',
        ),
    ]
