# Generated by Django 3.0.4 on 2020-04-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0016_auto_20200407_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='prestige',
            field=models.IntegerField(default=0),
        ),
    ]
