# Generated by Django 3.0.4 on 2020-04-08 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('playerdata', '0017_auto_20200407_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('char_limit', models.IntegerField(default=50)),
                ('coins', models.IntegerField(default=0)),
                ('hero_exp', models.IntegerField(default=0)),
            ],
        ),
    ]
