# Generated by Django 3.0.4 on 2020-04-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0018_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='gems',
            field=models.IntegerField(default=0),
        ),
    ]
