# Generated by Django 3.0.4 on 2020-04-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0019_inventory_gems'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='copies',
            field=models.IntegerField(default=1),
        ),
    ]
