# Generated by Django 3.0.4 on 2020-04-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0022_auto_20200422_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_name',
            field=models.TextField(default=''),
        ),
    ]
