# Generated by Django 3.0.4 on 2020-04-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0023_chat_chat_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', 'time_send'], name='playerdata__chat_id_2a54fa_idx'),
        ),
    ]
