# Generated by Django 3.0.4 on 2020-04-30 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playerdata', '0025_auto_20200429_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.AddField(
            model_name='friend',
            name='user_1',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friend_user_1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friend',
            name='user_2',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friend_user_2', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
