# Generated by Django 3.0.4 on 2020-05-04 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0026_auto_20200430_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('description', models.TextField(default='A description has not been set.')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playerdata.Chat')),
            ],
        ),
        migrations.CreateModel(
            name='ClanMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.Clan')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.UserInfo')),
            ],
        ),
    ]
