# Generated by Django 3.0.4 on 2020-05-04 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0029_auto_20200504_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clanmember',
            name='id',
        ),
        migrations.AlterField(
            model_name='clanmember',
            name='userinfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='playerdata.UserInfo'),
        ),
    ]
