# Generated by Django 3.0.4 on 2020-05-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0030_auto_20200504_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='elo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='clan',
            index=models.Index(fields=['elo'], name='playerdata__elo_aa2ccd_idx'),
        ),
    ]
