# Generated by Django 3.0.4 on 2020-05-12 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0033_auto_20200510_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.Clan')),
                ('userinfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='playerdata.UserInfo')),
            ],
        ),
    ]
