# Generated by Django 3.0.4 on 2020-05-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0034_clanrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profile_picture',
            field=models.IntegerField(default=0),
        ),
    ]
