# Generated by Django 3.0.4 on 2020-05-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0035_userinfo_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='profile_picture',
            field=models.IntegerField(default=0),
        ),
    ]
