# Generated by Django 3.0.4 on 2020-06-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0037_chatlastreadmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='total_damage_dealt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='total_damage_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='total_health_healed',
            field=models.IntegerField(default=0),
        ),
    ]
