# Generated by Django 3.0.4 on 2020-06-11 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0038_auto_20200610_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCharacterUsage',
            fields=[
                ('char_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='playerdata.BaseCharacter')),
                ('num_games', models.IntegerField()),
                ('num_wins', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='num_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='num_wins',
            field=models.IntegerField(default=0),
        ),
    ]
