# Generated by Django 3.0.4 on 2020-06-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0039_auto_20200611_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecharacterusage',
            name='num_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basecharacterusage',
            name='num_wins',
            field=models.IntegerField(default=0),
        ),
    ]
