# Generated by Django 3.0.4 on 2020-06-15 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('playerdata', '0040_auto_20200611_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='DungeonProgress',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('stage_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DungeonStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.IntegerField()),
                ('coins', models.IntegerField()),
                ('gems', models.IntegerField()),
                ('mob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.Placement')),
            ],
        ),
    ]
