# Generated by Django 3.0.4 on 2020-06-14 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('playerdata', '0041_dungeon_dungeonprogress_dungeonstage'), ('playerdata', '0042_auto_20200614_1942')]

    dependencies = [
        ('playerdata', '0040_auto_20200611_2330'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DungeonStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_num', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('coins', models.IntegerField()),
                ('gems', models.IntegerField()),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.Dungeon')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.BaseCharacter')),
            ],
        ),
        migrations.CreateModel(
            name='DungeonProgress',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.Dungeon')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.DungeonStage')),
            ],
        ),
    ]
