# Generated by Django 3.0.4 on 2020-06-14 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0041_dungeon_dungeonprogress_dungeonstage_squashed_0042_auto_20200614_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeonstage',
            name='enemy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.Placement'),
        ),
    ]
