# Generated by Django 3.0.4 on 2020-06-25 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0042_basequest_playerquestcumulative_playerquestdaily_playerquestweekly'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveWeeklyQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.BaseQuest')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveDailyQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.BaseQuest')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveCumulativeQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.BaseQuest')),
            ],
        ),
    ]
