# Generated by Django 3.0.4 on 2020-06-26 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playerdata', '0043_activecumulativequest_activedailyquest_activeweeklyquest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CumulativeTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('type', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='playerquestcumulative',
            name='progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.CumulativeTracker'),
        ),
    ]
