# Generated by Django 3.0.4 on 2020-07-06 16:50

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playerdata', '0044_auto_20200626_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('gems', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('char_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playerdata.BaseCharacter')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimedCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.BaseCode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
