# Generated by Django 3.0.4 on 2020-07-06 19:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0045_basecode_claimedcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecode',
            name='items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
