# Generated by Django 3.0.4 on 2020-07-27 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playerdata', '0047_auto_20200711_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=1)),
                ('round_expiration', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='userreferral',
            name='referral_code',
            field=models.TextField(unique=True),
        ),
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.BaseCharacter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_wins', models.IntegerField(default=0)),
                ('num_losses', models.IntegerField(default=0)),
                ('has_picked', models.BooleanField(default=False)),
                ('rewards_left', models.IntegerField(default=0)),
                ('fights_left', models.IntegerField(default=0)),
                ('is_eliminated', models.BooleanField(default=False)),
                ('defence_placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.Placement')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.Tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_win', models.BooleanField()),
                ('has_played', models.BooleanField(default=False)),
                ('round', models.IntegerField()),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to=settings.AUTH_USER_MODEL)),
                ('tournament_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.TournamentMember')),
            ],
        ),
    ]
