# Generated by Django 3.0.4 on 2020-07-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0048_auto_20200727_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmatch',
            name='is_win',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
