# Generated by Django 3.0.4 on 2020-08-04 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playerdata', '0049_auto_20200728_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentSelectionCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
