# Generated by Django 3.0.4 on 2020-08-06 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0050_tournamentselectioncards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='tournament_member',
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='attacker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.TournamentMember'),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='defender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='playerdata.TournamentMember'),
        ),
    ]
