# Generated by Django 3.0.4 on 2020-08-11 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0051_auto_20200806_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='char_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char_1', to='playerdata.Character'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='char_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char_2', to='playerdata.Character'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='char_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char_3', to='playerdata.Character'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='char_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char_4', to='playerdata.Character'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='char_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char_5', to='playerdata.Character'),
        ),
    ]
