# Generated by Django 3.0.4 on 2020-08-24 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0053_userinfo_tourney_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_tourney',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='round',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.Character'),
        ),
    ]
