# Generated by Django 3.0.4 on 2020-08-25 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0053_userinfo_tourney_elo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseitem',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='baseitem',
            name='attack_speed',
        ),
        migrations.RemoveField(
            model_name='baseitem',
            name='penetration',
        ),
        migrations.RemoveField(
            model_name='item',
            name='copies',
        ),
        migrations.AddField(
            model_name='baseitem',
            name='ar_flat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='ar_mult',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='attack_flat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='attack_mult',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='crit_flat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='crit_mult',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='gear_slot',
            field=models.CharField(choices=[('H', 'Hat'), ('A', 'Armor'), ('B', 'Boots'), ('W', 'Weapon'), ('T', 'Tricket'), ('C', 'Consumables')], default='C', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseitem',
            name='mana_tick_flat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='mana_tick_mult',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='mr_flat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='mr_mult',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='range_flat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='speed_flat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='speed_mult',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='armor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armor', to='playerdata.Item'),
        ),
        migrations.AddField(
            model_name='character',
            name='boots',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boots', to='playerdata.Item'),
        ),
        migrations.AddField(
            model_name='character',
            name='hat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hat', to='playerdata.Item'),
        ),
        migrations.AddField(
            model_name='character',
            name='trinket_1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trinket_1', to='playerdata.Item'),
        ),
        migrations.AddField(
            model_name='character',
            name='trinket_2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trinket_2', to='playerdata.Item'),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weapon', to='playerdata.Item'),
        ),
    ]
