# Generated by Django 3.0.4 on 2020-08-26 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0055_item_revamp'),
        ('playerdata', '0054_auto_20200824_1634'),
    ]

    operations = [
    ]
