# Generated by Django 3.0.4 on 2020-08-26 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0056_merge_20200826_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseitem',
            name='ar_flat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseitem',
            name='ar_mult',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseitem',
            name='attack_flat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseitem',
            name='attack_mult',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseitem',
            name='crit_flat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseitem',
            name='crit_mult',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseitem',
            name='mana_tick_flat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseitem',
            name='mana_tick_mult',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseitem',
            name='mr_flat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseitem',
            name='mr_mult',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseitem',
            name='range_flat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseitem',
            name='speed_flat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseitem',
            name='speed_mult',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='armor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armor', to='playerdata.Item'),
        ),
        migrations.AlterField(
            model_name='character',
            name='boots',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boots', to='playerdata.Item'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hat', to='playerdata.Item'),
        ),
        migrations.AlterField(
            model_name='character',
            name='trinket_1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trinket_1', to='playerdata.Item'),
        ),
        migrations.AlterField(
            model_name='character',
            name='trinket_2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trinket_2', to='playerdata.Item'),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weapon', to='playerdata.Item'),
        ),
    ]
