# Generated by Django 3.0.4 on 2020-08-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0058_userinfo_prev_tourney_elo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
