# Generated by Django 3.0.4 on 2020-09-07 02:16

from django.db import migrations, models
import django.db.models.deletion
import playerdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0059_auto_20200830_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='armor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armor', to='playerdata.Item', validators=[playerdata.models.SlotValidator('A')]),
        ),
        migrations.AlterField(
            model_name='character',
            name='boots',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boots', to='playerdata.Item', validators=[playerdata.models.SlotValidator('B')]),
        ),
        migrations.AlterField(
            model_name='character',
            name='hat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hat', to='playerdata.Item', validators=[playerdata.models.SlotValidator('H')]),
        ),
        migrations.AlterField(
            model_name='character',
            name='trinket_1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trinket_1', to='playerdata.Item', validators=[playerdata.models.SlotValidator('T')]),
        ),
        migrations.AlterField(
            model_name='character',
            name='trinket_2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trinket_2', to='playerdata.Item', validators=[playerdata.models.SlotValidator('T')]),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weapon', to='playerdata.Item', validators=[playerdata.models.SlotValidator('W')]),
        ),
    ]
