# Generated by Django 3.0.4 on 2020-09-07 02:17

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0060_auto_20200907_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseitem',
            name='effect_ids',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
