# Generated by Django 3.0.4 on 2020-09-06 01:10

from django.db import migrations, models
import django.db.models.deletion
import playerdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0060_item_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='prev_elo',
            field=models.IntegerField(default=0),
        ),
    ]
