# Generated by Django 3.0.4 on 2020-09-17 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
import playerdata.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playerdata', '0062_invalidreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playerdata.Team'),
        ),
    ]
