# Generated by Django 3.0.4 on 2020-09-18 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0064_auto_20200917_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='team',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
