# Generated by Django 3.0.4 on 2020-09-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0065_auto_20200918_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='is_tourney',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['user', 'is_tourney'], name='playerdata__user_id_0465a3_idx'),
        ),
    ]
