# Generated by Django 3.0.4 on 2020-10-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0066_auto_20200926_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='player_exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='player_level',
            field=models.IntegerField(default=0),
        ),
    ]
