# Generated by Django 3.0.4 on 2020-10-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0067_inventory_player_exp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dungeonstage',
            old_name='exp',
            new_name='player_exp',
        ),
    ]
