# Generated by Django 3.0.4 on 2020-10-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0068_auto_20201014_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='player_exp',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='player_exp',
            field=models.IntegerField(default=0),
        ),
    ]
