# Generated by Django 3.0.4 on 2020-10-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0069_auto_20201015_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('V', 'Version'), ('M', 'Maintenance')], max_length=1)),
                ('version_number', models.CharField(blank=True, max_length=15, null=True)),
                ('require_update', models.BooleanField(default=True)),
                ('maintenance_start', models.DateTimeField(blank=True, null=True)),
                ('expected_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='serverstatus',
            index=models.Index(fields=['creation_time', 'event_type'], name='playerdata__creatio_bc23b0_idx'),
        ),
    ]
