# Generated by Django 3.0.4 on 2020-10-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0070_auto_20201017_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basecharacter',
            old_name='attack',
            new_name='attack_damage',
        ),
        migrations.AddField(
            model_name='basecharacter',
            name='ability_damage',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
