# Generated by Django 3.0.4 on 2020-10-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0071_auto_20201018_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecharacter',
            name='ability_scale',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
