# Generated by Django 3.0.4 on 2020-10-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0072_basecharacter_ability_scale'),
        ('playerdata', '0070_auto_20201018_0323'),
    ]

    operations = [
    ]
