# Generated by Django 3.0.4 on 2020-10-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0074_auto_20201023_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='coins',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='gems',
            field=models.IntegerField(default=800),
        ),
    ]
