# Generated by Django 3.0.4 on 2020-11-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0075_auto_20201029_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='description',
            field=models.TextField(default='A description has not been set.'),
        ),
    ]
