# Generated by Django 3.0.4 on 2020-11-07 17:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0076_userinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecharacter',
            name='specs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basecharacter',
            name='char_type',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
