# Generated by Django 3.0.4 on 2020-11-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0077_auto_20201107_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='gems',
            field=models.IntegerField(default=5000),
        ),
    ]
