# Generated by Django 3.0.4 on 2020-11-14 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0079_userinfo_is_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='last_collected_rewards',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
