# Generated by Django 3.0.4 on 2020-11-14 23:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0079_userinfo_is_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='last_collected_rewards',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 23, 51, 29, 716662, tzinfo=utc)),
        ),
    ]
