# Generated by Django 3.0.4 on 2020-11-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0080_inventory_last_collected_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseitem',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
    ]
