# Generated by Django 3.0.4 on 2020-11-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0081_baseitem_is_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='cap',
            field=models.IntegerField(default=30),
        ),
    ]
