# Generated by Django 3.0.4 on 2020-11-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0082_clan_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecharacter',
            name='rollable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='basecharacter',
            index=models.Index(fields=['rarity', 'rollable'], name='playerdata__rarity_850b75_idx'),
        ),
    ]
