# Generated by Django 3.0.4 on 2020-11-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0083_auto_20201120_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='dust',
            field=models.IntegerField(default=100),
        ),
    ]
