# Generated by Django 3.0.4 on 2020-11-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0084_inventory_dust'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='essence',
            field=models.IntegerField(default=0),
        ),
    ]
