# Generated by Django 3.0.4 on 2020-11-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0086_inventory_is_auto_retire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='num_members',
            field=models.IntegerField(default=1),
        ),
    ]
