# Generated by Django 3.0.4 on 2020-11-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0087_auto_20201123_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basequest',
            name='total',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cumulativetracker',
            name='progress',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerquestdaily',
            name='progress',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerquestweekly',
            name='progress',
            field=models.BigIntegerField(default=0),
        ),
    ]
