# Generated by Django 3.0.4 on 2020-11-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0088_auto_20201124_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='basequest',
            name='dust',
            field=models.IntegerField(null=True),
        ),
    ]
