# Generated by Django 3.0.4 on 2020-11-30 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playerdata', '0089_basequest_dust'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.ActiveDeal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BaseDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gems', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('dust', models.IntegerField(default=0)),
                ('item_quantity', models.IntegerField(default=0)),
                ('deal_type', models.IntegerField(choices=[(0, 'DAILY'), (1, 'WEEKLY'), (2, 'MONTHLY')])),
                ('order', models.IntegerField(default=0)),
                ('char_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playerdata.BaseCharacter')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playerdata.BaseItem')),
            ],
        ),
        migrations.AddField(
            model_name='activedeal',
            name='base_deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.BaseDeal'),
        ),
        migrations.AddConstraint(
            model_name='purchasedtracker',
            constraint=models.UniqueConstraint(fields=('user', 'deal'), name='unique_purchase'),
        ),
        migrations.AddIndex(
            model_name='activedeal',
            index=models.Index(fields=['expiration_date'], name='playerdata__expirat_91e8a3_idx'),
        ),
    ]
