# Generated by Django 3.0.4 on 2020-11-30 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playerdata', '0089_basequest_dust'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gems', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('dust', models.IntegerField(default=0)),
                ('essence', models.IntegerField(default=0)),
                ('item_quantity', models.IntegerField(default=0)),
                ('essence_cost', models.IntegerField(default=0)),
                ('deal_type', models.IntegerField(choices=[(0, 'DAILY'), (1, 'WEEKLY'), (2, 'MONTHLY')])),
                ('order', models.IntegerField(default=0)),
                ('expiration_date', models.DateTimeField()),
                ('char_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playerdata.BaseCharacter')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playerdata.BaseItem')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.Deal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'deal')},
            },
        ),
    ]
