# Generated by Django 3.0.4 on 2020-11-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0090_auto_20201130_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedeal',
            name='gems_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basedeal',
            name='deal_type',
            field=models.IntegerField(choices=[(0, 'DAILY'), (1, 'WEEKLY'), (2, 'MONTHLY'), (3, 'GEMS_COST')]),
        ),
    ]
