# Generated by Django 3.0.4 on 2020-12-06 00:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import playerdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0091_auto_20201130_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCharacterAbility',
            fields=[
                ('char_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='playerdata.BaseCharacter')),
                ('ability1_specs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, validators=[playerdata.models.BaseCharacterAbility.validate_ability_specs])),
                ('ability2_specs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, validators=[playerdata.models.BaseCharacterAbility.validate_ability_specs])),
                ('ability3_specs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, validators=[playerdata.models.BaseCharacterAbility.validate_ability_specs])),
                ('ultimate_specs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, validators=[playerdata.models.BaseCharacterAbility.validate_ability_specs])),
            ],
        ),
    ]
