# Generated by Django 3.0.4 on 2020-12-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0094_auto_20201207_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecharacterability',
            name='ability1_desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='basecharacterability',
            name='ability2_desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='basecharacterability',
            name='ability3_desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='basecharacterability',
            name='ultimate_desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
