# Generated by Django 3.0.4 on 2020-12-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0096_auto_20201216_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseitem',
            name='max_health_flat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='max_health_mult',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
