# Generated by Django 3.0.4 on 2020-12-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0097_auto_20201219_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedtracker',
            name='purchase_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='purchasedtracker',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playerdata.ActiveDeal'),
        ),
    ]
