# Generated by Django 3.0.4 on 2020-12-28 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0100_auto_20201227_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecharacter',
            name='specs',
        ),
    ]
