# Generated by Django 3.0.4 on 2021-01-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0101_remove_basecharacter_specs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='copies',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dungeonstage',
            name='story_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
