# Generated by Django 3.0.4 on 2021-01-09 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0105_auto_20210109_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)]),
        ),
    ]
