# Generated by Django 3.0.4 on 2021-01-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0107_auto_20210113_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverstatus',
            name='patch_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='basecode',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='basequest',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clan',
            name='description',
            field=models.CharField(default='A description has not been set.', max_length=255),
        ),
        migrations.AlterField(
            model_name='clan',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invalidreceipt',
            name='order_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invalidreceipt',
            name='product_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='purchasedtracker',
            name='purchase_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchasedtracker',
            name='transaction_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='referraltracker',
            name='device_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userreferral',
            name='referral_code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
