# Generated by Django 3.0.4 on 2021-01-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0107_auto_20210113_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverstatus',
            name='patch_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
