# Generated by Django 3.0.4 on 2021-01-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0108_auto_20210118_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecode',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='basequest',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='clan',
            name='description',
            field=models.TextField(default='A description has not been set.'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invalidreceipt',
            name='order_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='invalidreceipt',
            name='product_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='purchasedtracker',
            name='purchase_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='purchasedtracker',
            name='transaction_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='referraltracker',
            name='device_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userreferral',
            name='referral_code',
            field=models.TextField(unique=True),
        ),
    ]
