# Generated by Django 3.0.4 on 2021-02-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0110_auto_20210125_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseitem',
            name='rollable',
            field=models.BooleanField(default=False),
        ),
    ]
