# Generated by Django 3.0.4 on 2021-02-18 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0113_basecharacter_starting_mana'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedeal',
            name='purchase_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='purchasedtracker',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playerdata.ActiveDeal'),
        ),
    ]
