# Generated by Django 3.0.4 on 2021-02-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0114_auto_20210218_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='gems_bought',
            field=models.IntegerField(default=0),
        ),
    ]
