# Generated by Django 3.0.4 on 2021-02-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0115_inventory_gems_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender_profile_picture_id',
            field=models.IntegerField(default=0),
        ),
    ]
