# Generated by Django 3.0.4 on 2021-02-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0116_chatmessage_sender_profile_picture_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='daily_dungeon_golden_ticket',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='daily_dungeon_ticket',
            field=models.IntegerField(default=0),
        ),
    ]
