# Generated by Django 3.0.4 on 2021-02-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0118_dailydungeonstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='daily_wins',
            field=models.IntegerField(default=0),
        ),
    ]
