# Generated by Django 3.0.4 on 2021-03-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0119_userstats_daily_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydungeonstatus',
            name='run_date',
            field=models.DateField(auto_now=True),
        ),
    ]
