# Generated by Django 3.0.4 on 2021-03-05 04:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import playerdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0121_dailydungeonstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCharacterAbility2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='0.0.0', max_length=30)),
                ('ability1_specs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, validators=[playerdata.models.BaseCharacterAbility2.validate_ability_specs])),
                ('ability1_desc', models.CharField(blank=True, max_length=250, null=True)),
                ('ability2_specs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, validators=[playerdata.models.BaseCharacterAbility2.validate_ability_specs])),
                ('ability2_desc', models.CharField(blank=True, max_length=250, null=True)),
                ('ability3_specs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, validators=[playerdata.models.BaseCharacterAbility2.validate_ability_specs])),
                ('ability3_desc', models.CharField(blank=True, max_length=250, null=True)),
                ('ultimate_specs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, validators=[playerdata.models.BaseCharacterAbility2.validate_ability_specs])),
                ('ultimate_desc', models.CharField(blank=True, max_length=250, null=True)),
                ('char_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.BaseCharacter')),
            ],
            options={
                'unique_together': {('char_type', 'version')},
            },
        ),
    ]
