# Generated by Django 3.0.4 on 2021-03-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0123_auto_20210309_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='best_daily_dungeon_stage',
            field=models.IntegerField(default=0),
        ),
    ]
