# Generated by Django 3.0.4 on 2021-03-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0125_auto_20210314_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseitem',
            name='attack_speed_flat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseprestige',
            name='attack_speed_flat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
