# Generated by Django 3.0.4 on 2021-03-24 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0128_invalidreceipt_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(default='A description has not been set.')),
                ('time_started', models.DateTimeField(auto_now_add=True)),
                ('elo', models.IntegerField(default=0)),
                ('profile_picture', models.IntegerField(default=0)),
                ('num_members', models.IntegerField(default=1)),
                ('cap', models.IntegerField(default=30)),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playerdata.Chat')),
            ],
        ),
        migrations.AddField(
            model_name='clanmember',
            name='clan2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='playerdata.Clan2'),
        ),
        migrations.AddField(
            model_name='clanrequest',
            name='clan2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='playerdata.Clan2'),
        ),
        migrations.AddIndex(
            model_name='clan2',
            index=models.Index(fields=['name'], name='playerdata__name_f6797c_idx'),
        ),
        migrations.AddIndex(
            model_name='clan2',
            index=models.Index(fields=['elo'], name='playerdata__elo_c3bebb_idx'),
        ),
    ]
