# Generated by Django 3.0.4 on 2021-03-27 15:27

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('playerdata', '0130_auto_20210326_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoevasionStatus',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('stage', models.IntegerField(default=0)),
                ('character_state', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='best_moevasion_stage',
            field=models.IntegerField(default=0),
        ),
    ]
