# Generated by Django 3.0.4 on 2021-03-28 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0132_basecharacterstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecharacter',
            name='ability_damage',
        ),
        migrations.RemoveField(
            model_name='basecharacter',
            name='ability_scale',
        ),
        migrations.RemoveField(
            model_name='basecharacter',
            name='ar',
        ),
        migrations.RemoveField(
            model_name='basecharacter',
            name='ar_scale',
        ),
        migrations.RemoveField(
            model_name='basecharacter',
            name='attack_damage',
        ),
        migrations.RemoveField(
            model_name='basecharacter',
            name='attack_range',
        ),
        migrations.RemoveField(
            model_name='basecharacter',
            name='attack_scale',
        ),
        migrations.RemoveField(
            model_name='basecharacter',
            name='attack_speed',
        ),
        migrations.RemoveField(
            model_name='basecharacter',
            name='crit_chance',
        ),
        migrations.RemoveField(
            model_name='basecharacter',
            name='health',
        ),
        migrations.RemoveField(
            model_name='basecharacter',
            name='health_scale',
        ),
        migrations.RemoveField(
            model_name='basecharacter',
            name='mana',
        ),
        migrations.RemoveField(
            model_name='basecharacter',
            name='mr',
        ),
        migrations.RemoveField(
            model_name='basecharacter',
            name='mr_scale',
        ),
        migrations.RemoveField(
            model_name='basecharacter',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='basecharacter',
            name='starting_mana',
        ),
        migrations.DeleteModel(
            name='BaseCharacterAbility',
        ),
    ]
