# Generated by Django 3.0.4 on 2021-03-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0133_auto_20210328_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeonboss',
            name='carry_id',
            field=models.IntegerField(default=-1),
        ),
    ]
