# Generated by Django 3.0.4 on 2021-03-30 00:57

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0135_auto_20210330_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='profile_pics',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
