# Generated by Django 3.0.4 on 2021-03-31 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0136_inventory_profile_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='highest_moevasion_reward_collected',
            field=models.IntegerField(default=0),
        ),
    ]
