# Generated by Django 3.0.4 on 2021-04-07 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('playerdata', '0137_userinfo_highest_moevasion_reward_collected'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMatchState',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('campaign_state', models.TextField(default='')),
                ('tower_state', models.TextField(default='')),
                ('tunnels_state', models.TextField(default='')),
                ('dailydungeon_state', models.TextField(default='')),
                ('moevasion_state', models.TextField(default='')),
            ],
        ),
    ]
