# Generated by Django 3.0.4 on 2021-04-07 04:37

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('playerdata', '0137_userinfo_highest_moevasion_reward_collected'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMatchState',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('campaign_state', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('tower_state', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('tunnels_state', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('dailydungeon_state', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('moevasion_state', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
