# Generated by Django 3.0.4 on 2021-04-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0138_usermatchstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanmember',
            name='clan',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playerdata.Clan'),
        ),
        migrations.AlterField(
            model_name='clanmember',
            name='clan2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playerdata.Clan2'),
        ),
    ]
