# Generated by Django 3.0.4 on 2021-04-12 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0139_auto_20210411_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clanmember',
            name='clan',
        ),
        migrations.RemoveField(
            model_name='clanrequest',
            name='clan',
        ),
        migrations.AlterField(
            model_name='clanrequest',
            name='clan2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.Clan2'),
        ),
        migrations.DeleteModel(
            name='Clan',
        ),
    ]
