# Generated by Django 3.0.4 on 2021-04-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0141_playerquestcumulative2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerQuestCumulative',
        ),
    ]
