# Generated by Django 3.0.4 on 2021-04-17 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playerdata', '0142_delete_playerquestcumulative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerquestcumulative2',
            name='id',
        ),
        migrations.AlterField(
            model_name='playerquestcumulative2',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
