# Generated by Django 3.0.4 on 2021-04-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0143_auto_20210417_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanmember',
            name='is_elder',
            field=models.BooleanField(default=False),
        ),
    ]
