# Generated by Django 3.0.4 on 2021-04-26 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('playerdata', '0144_clanmember_is_elder'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPTracker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ip_list', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('suspicious', models.BooleanField(default=False)),
            ],
        ),
    ]
