# Generated by Django 3.0.4 on 2021-04-27 06:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0145_iptracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='attacker_elo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='attacker_team',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='defender_elo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='defender_team',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('Q', 'Quickplay')], default='Q', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='seed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='version',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
