# Generated by Django 3.0.4 on 2021-04-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0149_auto_20210428_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='tier_rank',
            field=models.IntegerField(choices=[(1, 'BRONZE_TWO'), (2, 'BRONZE_ONE'), (3, 'SILVER_TWO'), (4, 'SILVER_ONE'), (5, 'GOLD_TWO'), (6, 'GOLD_ONE'), (7, 'PLAT_TWO'), (8, 'PLAT_ONE'), (9, 'DIAMOND_TWO'), (10, 'DIAMOND_ONE'), (11, 'MASTER')], default=1),
        ),
    ]
