# Generated by Django 3.0.4 on 2021-05-02 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('playerdata', '0151_auto_20210430_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='EloRewardTracker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('completed', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None)),
                ('claimed', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='highest_elo',
            field=models.IntegerField(default=0),
        ),
    ]
