# Generated by Django 3.0.4 on 2021-05-05 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playerdata', '0152_auto_20210503_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('value', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=False)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.Flag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'flag')},
            },
        ),
    ]
