# Generated by Django 3.0.4 on 2021-05-19 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playerdata', '0158_auto_20210516_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanPVEResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss', models.CharField(choices=[('1', 'The Wall'), ('2', 'One Shot Wonder'), ('3', 'AOE Boss')], max_length=1)),
                ('best_score', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='clan2',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='clan2',
            index=models.Index(fields=['exp'], name='playerdata__exp_11354a_idx'),
        ),
        migrations.AddField(
            model_name='clanpveresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='clanpveresult',
            unique_together={('user', 'boss')},
        ),
    ]
