# Generated by Django 3.0.4 on 2021-05-20 21:42

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import playerdata.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playerdata', '0160_clanpvestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanpvestatus',
            name='character_lending',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='clanpvestatus',
            name='tickets_1',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=playerdata.models.clan_pve_ticket_default),
        ),
        migrations.AddField(
            model_name='clanpvestatus',
            name='tickets_2',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=playerdata.models.clan_pve_ticket_default),
        ),
        migrations.AddField(
            model_name='clanpvestatus',
            name='tickets_3',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=playerdata.models.clan_pve_ticket_default),
        ),
        migrations.CreateModel(
            name='ClanPVEEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.Clan2')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('clan', 'date')},
            },
        ),
        migrations.AddField(
            model_name='clanpvestatus',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='playerdata.ClanPVEEvent'),
        ),
        migrations.AlterUniqueTogether(
            name='clanpvestatus',
            unique_together={('user', 'event')},
        ),
        migrations.RemoveField(
            model_name='clanpvestatus',
            name='day',
        ),
        migrations.RemoveField(
            model_name='clanpvestatus',
            name='tickets',
        ),
    ]
