# Generated by Django 3.0.4 on 2021-05-20 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('playerdata', '0161_auto_20210520_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelicShop',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('purchased_relics', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='relic_stones',
            field=models.IntegerField(default=0),
        ),
    ]
