# Generated by Django 3.0.4 on 2021-05-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0162_auto_20210520_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='pvp_skips',
            field=models.IntegerField(default=5),
        ),
    ]
