# Generated by Django 3.0.4 on 2021-05-23 00:51

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0164_auto_20210521_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanmember',
            name='pve_character_lending',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
