# Generated by Django 3.0.4 on 2021-05-28 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('playerdata', '0165_clanmember_pve_character_lending'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampBadgeTracker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_completed', models.IntegerField(default=-1)),
                ('last_claimed', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='champ_badges',
            field=models.IntegerField(default=0),
        ),
    ]
