# Generated by Django 3.0.4 on 2021-06-14 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('playerdata', '0167_auto_20210612_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('legendaries', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('epics', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('rares', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
