# Generated by Django 3.0.4 on 2021-06-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0170_worldpack'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='gold_chest_counter',
            field=models.IntegerField(default=0),
        ),
    ]
