# Generated by Django 3.0.4 on 2021-07-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0172_userinfo_highest_season_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_monthly_sub',
            field=models.BooleanField(default=False),
        ),
    ]
