# Generated by Django 3.0.4 on 2021-07-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0173_userinfo_is_monthly_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='pet_points',
            field=models.IntegerField(default=0),
        ),
    ]
