# Generated by Django 3.0.4 on 2021-07-15 20:24

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('playerdata', '0174_inventory_pet_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryMode',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('available_stories', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('completed_stories', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('buff_points', models.IntegerField(default=0)),
                ('current_tier', models.IntegerField(default=0)),
                ('current_lvl', models.IntegerField(default=0)),
                ('num_runs', models.IntegerField(default=0)),
                ('story_id', models.IntegerField(default=-1)),
                ('character_state', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='is_story',
            field=models.BooleanField(default=False),
        ),
    ]
