# Generated by Django 3.0.4 on 2021-07-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0175_auto_20210715_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storymode',
            name='current_tier',
            field=models.IntegerField(default=-1),
        ),
    ]
