# Generated by Django 3.0.4 on 2021-07-17 20:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0176_auto_20210716_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='storymode',
            name='boons',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
