# Generated by Django 3.0.4 on 2021-07-19 02:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0177_storymode_boons'),
    ]

    operations = [
        migrations.AddField(
            model_name='storymode',
            name='pregame_buffs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
