# Generated by Django 3.0.4 on 2021-07-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0178_storymode_pregame_buffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='vip_exp',
            field=models.IntegerField(default=0),
        ),
    ]
