# Generated by Django 3.0.4 on 2021-07-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0179_userinfo_vip_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecharacterstats',
            name='ability_ticks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
