# Generated by Django 3.0.4 on 2021-07-27 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playerdata', '0180_basecharacterstats_ability_ticks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonreward',
            name='is_claimed',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sender_profile_picture_id', models.IntegerField(default=0)),
                ('time_send', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playerdata.BaseCode')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailreceiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailsender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='mail',
            index=models.Index(fields=['time_send'], name='playerdata__time_se_b2b3a0_idx'),
        ),
    ]
