# Generated by Django 3.0.4 on 2021-08-02 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0182_rotatingmodestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='RogueAllowedAbilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_type', models.CharField(choices=[('1', 'Ability1'), ('2', 'Ability2'), ('3', 'Ability3'), ('U', 'Ultimate')], max_length=1)),
                ('allowed', models.BooleanField(default=False)),
                ('char_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.BaseCharacter')),
            ],
            options={
                'unique_together': {('char_type', 'ability_type')},
            },
        ),
    ]
