# Generated by Django 3.0.4 on 2021-08-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0183_rogueallowedabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='rogueallowedabilities',
            name='is_passive',
            field=models.BooleanField(default=False),
        ),
    ]
