# Generated by Django 3.0.4 on 2021-09-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0185_mail_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='is_reward_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
