# Generated by Django 3.0.4 on 2021-09-14 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('playerdata', '0186_mail_has_unclaimed_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegalRewards',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_premium', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('last_completed', models.IntegerField(default=-1)),
                ('last_claimed', models.IntegerField(default=-1)),
            ],
        ),
    ]
