# Generated by Django 3.0.4 on 2021-09-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0188_auto_20210915_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='epic_shards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='legendary_shards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='rare_shards',
            field=models.IntegerField(default=0),
        ),
    ]
