# Generated by Django 3.0.4 on 2021-09-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0189_auto_20210917_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedtracker',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
