# Generated by Django 3.0.4 on 2021-09-23 17:33

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields
import playerdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0189_auto_20210917_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='active_pet_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='pets_unlocked',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), default=playerdata.models.default_pets_unlocked, size=None),
        ),
    ]
