# Generated by Django 3.0.4 on 2021-09-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0191_purchasedtracker_is_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydungeonstatus',
            name='tier',
            field=models.IntegerField(default=0),
        ),
    ]
