# Generated by Django 3.0.4 on 2021-09-28 22:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0192_dailydungeonstatus_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='cumulative_stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
