# Generated by Django 3.0.4 on 2021-09-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0193_userstats_cumulative_stats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CumulativeTracker',
        ),
    ]
