# Generated by Django 3.0.4 on 2021-10-02 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
import playerdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('playerdata', '0194_delete_cumulativetracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='AFKReward',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('unclaimed_gold', models.IntegerField(default=0)),
                ('unclaimed_dust', models.IntegerField(default=0)),
                ('unclaimed_shards', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), default=playerdata.models.default_afk_shard_list, size=None)),
                ('leftover_shards', models.FloatField(default=0)),
                ('last_eval_time', models.DateTimeField(auto_now_add=True)),
                ('consumed_rune_time', models.IntegerField(default=0)),
                ('runes_left', models.IntegerField(default=0)),
            ],
        ),
    ]
