# Generated by Django 3.0.4 on 2021-10-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0195_afkreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='afkreward',
            name='leftover_shards',
            field=models.FloatField(default=0),
        ),
    ]
