# Generated by Django 3.0.4 on 2021-10-04 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('playerdata', '0195_afkreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRewards',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_claimed_reward', models.IntegerField(default=-1)),
            ],
        ),
    ]
