# Generated by Django 3.0.4 on 2021-10-14 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0198_auto_20211008_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanrequest',
            name='userinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.UserInfo'),
        ),
    ]
