# Generated by Django 3.0.4 on 2021-10-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0199_creatorcode_creatorcodetracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorcodetracker',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='creatorcodetracker',
            name='device_id',
            field=models.TextField(null=True),
        ),
    ]
