# Generated by Django 3.0.4 on 2021-10-14 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0199_creatorcode_creatorcodetracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorcodetracker',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='playerdata.CreatorCode'),
        ),
    ]
