# Generated by Django 3.0.4 on 2021-10-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0200_creatorcode_creatorcodetracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecharacterusage',
            name='last_reset_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
