# Generated by Django 3.0.4 on 2021-10-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0200_creatorcode_creatorcodetracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedeal',
            name='epic_shards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basedeal',
            name='legendary_shards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basedeal',
            name='rare_shards',
            field=models.IntegerField(default=0),
        ),
    ]
