# Generated by Django 3.0.4 on 2021-10-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0201_auto_20211023_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecharacterusage',
            name='last_reset_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
