# Generated by Django 3.0.4 on 2021-10-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0202_basecharacterusage_last_reset_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorcode',
            name='gems_earned',
            field=models.IntegerField(default=0),
        ),
    ]
