# Generated by Django 3.0.4 on 2021-10-25 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0202_basecharacterusage_last_reset_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afkreward',
            old_name='runes_to_be_converted',
            new_name='rune_ticks',
        ),
        migrations.AddField(
            model_name='afkreward',
            name='leftover_dust_ticks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='afkreward',
            name='leftover_gold_ticks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='afkreward',
            name='last_eval_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
