# Generated by Django 3.0.4 on 2021-10-27 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0203_auto_20211026_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afkreward',
            old_name='leftover_shard_intervals',
            new_name='leftover_shard_interval',
        ),
    ]
