# Generated by Django 3.0.4 on 2021-10-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0204_auto_20211027_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorcode',
            name='gems_earned',
            field=models.IntegerField(default=0),
        ),
    ]
