# Generated by Django 3.0.4 on 2021-10-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0205_creatorcode_gems_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorcode',
            name='gems_claimable',
            field=models.IntegerField(default=0),
        ),
    ]
