# Generated by Django 3.0.4 on 2021-11-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0206_creatorcode_gems_claimable'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='daily_games',
            field=models.IntegerField(default=0),
        ),
    ]
