# Generated by Django 3.0.4 on 2021-11-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0207_userstats_daily_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTimeTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
