# Generated by Django 3.0.4 on 2021-11-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0209_auto_20211102_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afkreward',
            name='unclaimed_converted_runes',
        ),
    ]
