# Generated by Django 3.0.4 on 2021-11-11 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('playerdata', '0210_remove_afkreward_unclaimed_converted_runes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrassEvent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cur_floor', models.IntegerField(default=0)),
                ('ladder_index', models.IntegerField(default=-1)),
                ('tickets_left', models.IntegerField(default=0)),
                ('tokens_left', models.IntegerField(default=0)),
                ('tokens_bought', models.IntegerField(default=0)),
            ],
        ),
    ]
