# Generated by Django 3.0.4 on 2021-11-14 01:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0211_grassevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='grassevent',
            name='claimed_tiles',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='grassevent',
            name='floor_reward_map',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
