# Generated by Django 3.0.4 on 2021-11-16 20:49

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields
import playerdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0212_auto_20211114_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='pets_unlocked',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=playerdata.models.default_pets_unlocked, null=True, size=None),
        ),
    ]
