# Generated by Django 3.0.4 on 2021-11-15 16:36

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields
import playerdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0212_auto_20211114_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grassevent',
            name='floor_reward_map',
        ),
        migrations.AddField(
            model_name='grassevent',
            name='rewards_left',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), default=playerdata.models.default_grass_rewards_left, size=None),
        ),
    ]
