# Generated by Django 3.0.4 on 2021-11-20 05:39

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields
import playerdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0214_auto_20211118_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grassevent',
            name='tickets_left',
        ),
        migrations.AddField(
            model_name='grassevent',
            name='unclaimed_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grassevent',
            name='claimed_tiles',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='grassevent',
            name='rewards_left',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=playerdata.models.default_grass_rewards_left, null=True, size=None),
        ),
    ]
