# Generated by Django 3.0.4 on 2021-11-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0215_auto_20211120_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grassevent',
            name='grass_cuts_left',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='grassevent',
            name='unclaimed_tokens',
            field=models.IntegerField(default=3),
        ),
    ]
