# Generated by Django 3.0.4 on 2021-11-24 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0216_auto_20211122_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
