# Generated by Django 3.0.4 on 2021-11-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0218_auto_20211125_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='coins_fast_reward_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='dust_fast_reward_hours',
            field=models.IntegerField(default=0),
        ),
    ]
