# Generated by Django 3.0.4 on 2021-11-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0219_auto_20211126_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecharacterusage',
            name='num_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basecharacterusage',
            name='num_wins',
            field=models.IntegerField(default=0),
        ),
    ]
