# Generated by Django 3.0.4 on 2021-11-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0219_auto_20211126_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='replay_id',
            field=models.IntegerField(default=-1),
        ),
    ]
