# Generated by Django 3.0.4 on 2021-12-01 18:47

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields
import playerdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0221_auto_20211130_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='DungeonStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dungeon_type', models.IntegerField(unique=True)),
                ('wins_by_stage', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), default=playerdata.models.default_dungeonstats_array, size=None)),
                ('games_by_stage', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), default=playerdata.models.default_dungeonstats_array, size=None)),
            ],
        ),
    ]
