# Generated by Django 3.0.4 on 2021-12-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0221_auto_20211130_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='DungeonStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField()),
                ('dungeon_type', models.IntegerField(choices=[(0, 'CAMPAIGN'), (1, 'TOWER'), (2, 'TUNNELS')])),
                ('wins', models.IntegerField(default=0)),
                ('games', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddConstraint(
            model_name='dungeonstats',
            constraint=models.UniqueConstraint(fields=('stage', 'dungeon_type'), name='unique_stage_stat'),
        ),
    ]
