# Generated by Django 3.0.4 on 2021-12-08 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0222_auto_20211201_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrewards',
            name='last_claimed_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
