# Generated by Django 3.0.4 on 2021-12-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0224_auto_20211213_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedeal',
            name='coins_fast_reward_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basedeal',
            name='dust_fast_reward_hours',
            field=models.IntegerField(default=0),
        ),
    ]
