# Generated by Django 3.0.4 on 2021-12-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0225_auto_20211214_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackeralert',
            name='match_simulated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackeralert',
            name='match_simulated_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackeralert',
            name='match_simulated_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hackeralert',
            name='skip_simulation',
            field=models.BooleanField(default=False),
        ),
    ]
