# Generated by Django 3.0.4 on 2021-12-16 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0225_auto_20211214_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackeralert',
            name='suspicious_match_id',
        ),
        migrations.AddField(
            model_name='hackeralert',
            name='match_simulated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackeralert',
            name='match_simulated_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackeralert',
            name='match_simulated_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hackeralert',
            name='skip_simulation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackeralert',
            name='suspicious_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playerdata.Match'),
        ),
    ]
