# Generated by Django 3.0.4 on 2021-12-17 19:22

from django.db import migrations, models
import playerdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0226_auto_20211216_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrewards',
            name='last_claimed_time',
            field=models.DateTimeField(default=playerdata.models.default_event_last_claimed_time),
        ),
    ]
