# Generated by Django 3.0.4 on 2021-12-27 16:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import playerdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0227_auto_20211217_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeonstage',
            name='char_dialog',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, validators=[playerdata.models.validate_char_dialog]),
        ),
    ]
