# Generated by Django 3.0.4 on 2022-01-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0228_auto_20211227_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecharacterstats',
            name='starting_ability_ticks',
            field=models.IntegerField(default=0),
        ),
    ]
