# Generated by Django 3.0.4 on 2022-01-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0231_auto_20220118_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceshop',
            name='is_refreshed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='regalrewards',
            name='last_completed',
            field=models.IntegerField(default=0),
        ),
    ]
