# Generated by Django 3.0.4 on 2022-02-06 19:52

from django.db import migrations, models
import playerdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0232_auto_20220128_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterrewardpack',
            name='expiration_date',
            field=models.DateTimeField(default=playerdata.models.chapter_rewards_pack_deadline),
        ),
        migrations.AddField(
            model_name='regalrewards',
            name='expiration_date',
            field=models.DateTimeField(default=playerdata.models.regal_rewards_refreshdate),
        ),
        migrations.AddField(
            model_name='worldpack',
            name='expiration_date',
            field=models.DateTimeField(default=playerdata.models.world_pack_default_expiration),
        ),
    ]
