# Generated by Django 3.0.4 on 2022-02-15 21:49

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0234_auto_20220208_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldpack',
            name='is_claimed',
        ),
        migrations.AddField(
            model_name='worldpack',
            name='purchased_packs',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
