# Generated by Django 3.0.4 on 2022-02-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0235_auto_20220215_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grassevent',
            old_name='grass_cuts_left',
            new_name='dynamite_left',
        ),
        migrations.RenameField(
            model_name='grassevent',
            old_name='unclaimed_tokens',
            new_name='unclaimed_dynamite',
        ),
        migrations.RemoveField(
            model_name='grassevent',
            name='tokens_bought',
        ),
        migrations.AddField(
            model_name='grassevent',
            name='tickets',
            field=models.IntegerField(default=0),
        ),
    ]
