# Generated by Django 3.0.4 on 2022-03-11 22:34

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0236_auto_20220219_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelbooster',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='levelbooster',
            name='is_enhanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='levelbooster',
            name='top_five',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='levelbooster',
            name='booster_level',
            field=models.IntegerField(default=0),
        ),
    ]
