# Generated by Django 3.0.4 on 2022-03-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0237_auto_20220311_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelbooster',
            name='unlocked_slots',
            field=models.IntegerField(default=0),
        ),
    ]
