# Generated by Django 3.0.4 on 2022-03-25 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0239_auto_20220322_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storymode',
            old_name='current_lvl',
            new_name='current_quest',
        ),
        migrations.RemoveField(
            model_name='storymode',
            name='num_runs',
        ),
    ]
