# Generated by Django 3.0.4 on 2022-03-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0239_auto_20220322_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storymode',
            name='current_lvl',
        ),
        migrations.RemoveField(
            model_name='storymode',
            name='num_runs',
        ),
        migrations.AddField(
            model_name='storymode',
            name='last_complete_quest',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='storymode',
            name='last_quest_reward_claimed',
            field=models.IntegerField(default=-1),
        ),
    ]
