# Generated by Django 3.0.4 on 2022-03-29 23:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0241_storyquest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpeditionMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_id', models.IntegerField(default=-1)),
                ('version', models.CharField(default='0.0.0', max_length=30)),
                ('map_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('char_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.BaseCharacter')),
            ],
            options={
                'unique_together': {('char_type', 'version', 'quest_id')},
            },
        ),
    ]
