# Generated by Django 3.0.4 on 2022-03-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0243_afkreward_unclaimed_ember'),
    ]

    operations = [
        migrations.AddField(
            model_name='expeditionmap',
            name='map_str',
            field=models.TextField(blank=True, default=''),
        ),
    ]
