# Generated by Django 3.0.4 on 2022-03-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0243_afkreward_unclaimed_ember'),
    ]

    operations = [
        migrations.AddField(
            model_name='expeditionmap',
            name='map_str',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='expeditionmap',
            name='game_mode',
            field=models.IntegerField(choices=[(0, 'QuickPlay'), (1, 'Dungeon'), (2, 'Tournament'), (3, 'DailyDungeon'), (4, 'Moevasion'), (5, 'Sandbox'), (6, 'Replay'), (7, 'ClanPVE'), (8, 'MoveTester'), (9, 'Roguelike'), (10, 'AFKBattle'), (11, 'TurkeyRoguelike'), (12, 'StoryRoguelike')], default=9),
        ),
    ]
