# Generated by Django 3.0.4 on 2022-04-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0246_userstats_fortune_pity_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='fortune_chests_purchased',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='mythical_chests_purchased',
            field=models.IntegerField(default=0),
        ),
    ]
