version: 2

jobs:
  build-and-test:
    working_directory: ~/battlegame_server
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: u_battlegame
          POSTGRES_DB: battlegame
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: "Set up .env"
          command: |
            echo -e "SECRET_KEY=foo\nPOSTGRES_PASSWORD=postgres" >> .env
      - run:
          command: |
            pipenv run python manage.py test
  deploy-prod:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v circleci@salutationstudio.com "./deploy.sh"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      # Optionally we can have a manual approval step in the future. For now
      # let it auto deploy on push to master.
      # - hold:
      #     type: approval
      #     requires:
      #       - build-and-test
      - deploy-prod:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
